package com.zyprex.txel

val extMimeMapMultiple = mapOf(
    "text/plain" to listOf("txt", "asc", "org", "conf", "log",
        "ini", "yaml", "toml", "diff", "bat", "cmd"),
    "text/x-c" to listOf("c", "cpp", "cxx", "h"),
    "text/html" to listOf("html", "htm"),
    "image/jpeg" to listOf("jpeg", "jpg"),
    "image/tiff" to listOf("tiff", "tif"),
    "audio/mpeg" to listOf("mp3", "mp2", "mp1", "mpeg", "mpg"),
    "audio/midi" to listOf("midi", "mid"),
    "audio/webm" to listOf("webm", "weba"),
    "audio/ogg" to listOf("ogg", "oga"),
    "application/vnd.rn-realmedia" to listOf("rmvb", "rm"),
    "application/html+xml" to listOf("xhtml", "xhtm"),
    "application/vnd.microsoft.portable-executable" to listOf("exe", "dll"),
    "application/vnd.sqlite3" to listOf("db", "sqlite", "sqlite3"),
)

val extMimeMap = mapOf(
    "text/markdown" to "md",
    "text/x-opml" to "opml" ,
    "text/css" to "css",
    "text/csv" to "csv",
    "text/x-java-source" to "java",
    "text/x-python" to "py",

    "image/gif" to "gif",
    "image/png" to "png",
    "image/bmp" to "bmp",
    "image/webp" to "webp",
    "image/svg+xml" to "svg",
    "image/vnd.microsoft.icon" to "ico",

    "audio/wav" to "wav",
    "audio/aac" to "aac",
    "audio/mpeg-url" to "m3u",
    "audio/x-aiff" to "aiff",
    "audio/flac" to "flac",
    "audio/alac" to "alac",
    "audio/x-ms-wma" to "wma",
    "audio/mp4a-latm" to "m4a",

    "video/mp4" to "mp4",
    "video/avi" to "avi",
    "video/ogg" to "ogv",
    "video/x-ms-wmv" to "wmv",
    "video/x-flv" to "flv",
    "video/quicktime" to "mov",
    "video/mp2t" to "ts",
    "video/3gpp" to "3gp",
    "video/dvd" to "vob",
    "video/x-matroska" to "mkv",

    "font/otf" to "otf",
    "font/ttf" to "ttf",
    "font/woff" to "woff",
    "font/woff2" to "woff2",

    "application/javascript" to "js",
    "application/x-shockwave-flash" to "swf",
    "application/rtf" to "rtf",
    "application/vnd.oasis.opendocument.text" to "odt",
    "application/vnd.oasis.opendocument.spreadsheet" to "ods",
    "application/vnd.visio" to "vsd",
    "application/msword" to "doc",
    "application/vnd.ms-powerpoint" to "ppt",
    "application/vnd.ms-excel" to "xls",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document" to "docx",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation" to "pptx",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" to "xlsx",
    "application/vnd.apple.mpegurl" to "m3u8",
    "application/pdf" to "pdf",
    "application/vnd.android.package-archive" to "apk",
    "application/zip" to "zip",
    "application/x-7z-compressed" to "7z",
    "application/xml" to "xml",
    "application/atom+xml" to "atom",
    "application/vnd.ms-htmlhelp" to "chm",
    "application/java" to "class",
    "application/java-archive" to "jar",
    "application/epub+zip" to "epub",
    "application/x-pilot-prc" to "prc",
    "application/x-fictionbook" to "fb2",
    "application/x-mobipocket-ebook" to "mobi",
    "application/x-mobi8-ebook" to "azw3",
    "application/vnd.amazon.ebook" to "azw",
    "application/gzip" to "gz",
    "application/x-bzip" to "bz",
    "application/x-bzip2" to "bz2",
    "application/vnd.rar" to "rar",
    "application/x-httpd-php" to "php",
    "application/json" to "json",
    "application/ld+json" to "jsonld",
    "application/x-latex" to "latex",
    "application/x-tar" to "tar",
    "application/x-csh" to "csh",
    "application/x-script.zsh" to "zsh",
    "application/x-sh" to "sh",
)